name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r7kamura/rust-problem-matchers@v1

      - name: Run Clippy Warnings
        run: cargo clippy --all-targets --all-features

      - name: Run Format Check
        run: cargo fmt --all -- --check

      - name: Run Build Check
        run: cargo check --all --all-targets --all-features

      - name: Run Check License
        run: |
          cargo install cargo-lichking
          cargo lichking check
